spring:
  application:
    name: provider

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true

server:
  port: 8081

logging:
  level:
    root: INFO #(TRACE, DEBUG, INFO, WARN, ERROR)
    com.example.provider: TRACE
  file:
    name: logs/${spring.application.name}.log
  logback:
    rollingpolicy:
      max-file-size: 5MB
      max-history: 7 # It stores them for 7 days

management:
  endpoints:
    web:
      exposure:
        include: "*"