spring:
  application:
    name: eureka

server:
  port: 8761

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false

logging:
  level:
    root: INFO #(TRACE, DEBUG, INFO, WARN, ERROR)
  file:
    name: logs/${spring.application.name}.log
  logback:
    rollingpolicy:
      max-file-size: 5MB
      max-history: 7 # It stores them for 7 days

management:
  endpoints:
    web:
      exposure:
        include: "*"